### ISSUE TITLE
deploy-ebpf.ps1 tries to deploy a file that is missing

### ISSUE THREAD

**Issue by Austin-Lamb** [microsoft/ebpf-for-windows#3358] opened 2024-03-15 22:51 UTC
### Describe the bug

When using `deploy-ebpf.ps1 -l` as recommended in Method 2 of the installation instructions ( https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md ), it tries to deploy `ebpfforwindows_memory.wprp` which is not present after I build.

I assume this file should just be removed from the list in the `deploy-ebpf` script, but perhaps it's suposed to be present and isn't building/generating somehow?  I can't find any other reference to this file in the repo.

### Steps taken to reproduce bug

1. Build
2. `.\x64\Debug\deploy-ebpf.ps1 -l`

### Expected behavior

Deploys eBPF to temp folder per the docs

### Actual outcome

```
Copy-Item : Cannot find path 'C:\Repos\ebpf-for-windows\x64\Debug\ebpfforwindows_memory.wprp' because it does not exist.
At C:\Repos\ebpf-for-windows\x64\Debug\deploy-ebpf.ps1:314 char:7
+       Copy-Item "$source_path" -Destination "$destination_path" -Erro ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Repos\ebpf-f...ows_memory.wprp:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Comment by Austin-Lamb** [comment] 2024-03-15 22:53
I tried manually removing this file from the list of files in `deploy-ebpf.ps1` and there are other missing files (like `common.psm1`).  So perhaps the `deploy-ebpf` script has not been maintained?  Is this still a supported way to deploy locally built bits and test?

**Comment by dahavey** [comment] 2024-03-18 15:58
Duplicate of #2422

**Closed by dahavey** 2024-03-18 15:58 UTC
Labels: bug, triaged
