### ISSUE TITLE
eBPF does not support helper functions that modify direct packet data

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#3090] opened 2023-11-30 18:25 UTC
### Describe the bug

On Linux, several BPF helpers are documented as potentially invalidating the direct packet access pointers (e.g. `data` and `data_end`), and so the verifier checks the pointers are re-validated by the program after the helper returns.

Is this implemented for Windows helpers? Would this be provided by the `reallocate_packet` field in the ebpf-verifier project?

Example from the Linux man pages for the `bpf_skb_pull_data` function:

> A call to this helper is susceptible to change the underlying packet buffer.
Therefore, at load time, all checks on pointers previously done by the
verifier are invalidated and must be performed again, if the helper is used
in combination with direct packet access.

### OS information

N/A.

### Steps taken to reproduce bug

Attempt to implement an extension that modifies the direct packet access pointers, and discover there is no characteristic to indicate the modification to the verifier.

### Expected behavior

A helper that modifies packet data should indicate to eBPF, and the verifier should require programs revalidate data after calling the helper.

### Actual outcome

There is no field that can be set to indicate this behavior to eBPF. Helpers today do not invalidate packet data by default.

**Comment by shankarseal** [comment] 2023-12-01 01:48
Thanks for creating this issue @mtfriesen . The issue is understood. We will triage it next week and get it fixed in eBPF for Windows.

**Comment by dthaler** [comment] 2023-12-01 01:56
This is the `.reallocate_packet` member of EbpfHelperPrototype.
`get_helper_prototype_windows()` in libs\api_common\windows_helpers.cpp returns this struct but always leaves that member 0 (no code to ever set it to anything else).

**Closed** 2023-12-11 18:41 UTC
Labels: bug, triaged
