### ISSUE TITLE
detach / unlink IOCTL missing from execution context.

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#334] opened 2021-07-08 06:53 UTC
There needs to be an explicit DETACH / UNLINK IOCTL (which takes link handle as input) to detach a program from a hook. Simply closing the link handle should not detach the program from the hook.

**Comment by poornagmsft** [comment] 2021-07-09 03:38
@saxena-anurag I have assigned this issue to you.

**Comment by poornagmsft** [comment] 2021-07-26 15:27
@saxena-anurag  i have moved this to 2108.

**Comment by Alan-Jowett** [comment] 2021-07-28 15:33
Can you please clarify what the lifecycle for links looks like? Based on the ask above:

1) Link object & handle are created when a program is attached to a hook.
2) Link handle and program handle are closed.
3) User gets a new handle to link object (how)?
4) User issues link detach on the new handle.
5) Link object releases its reference to the program object.
6) Program object is destroyed.
7) Link handle is closed.
8) Link object is destroyed. 

The current model is:
A link handle holds a reference to the link object.
A link object holds a reference to a program.
A program holds a reference to maps.

The problem is that the link object depends on the program object. The link object is the root of the dependency graph, so not cleaning up when we close the link handle means we leak link objects, program objects, and map objects.

**Comment by saxena-anurag** [comment] 2021-07-28 16:20
Hi Alan, I have already made most of the changes needed for this, will publish the PR mostly by EOW

The object lifecycle should be as follows:

1. When attach is done, link object should be created and attached, with 2 ref count on link object ("handle" ref and "attach" ref). An extra ref should not be taken on program object in this step. Instead the program object will maintain a list of all the link objects it is attached to.
2. Since link object has 2 refs, one will be released when detach is called, other will be released with link handle is closed.
3. If program ref count becomes 0 before link ref count becomes 0, program cleanup code will iterate over the list of link objects in the program object and call "detach" on the link object. This will cause the "attach" ref taken in step 1 to be released.
4. When ref count of link object becomes 0, the object will be deleted.

Consider the following example:

1. ebpf program is loaded.
2. program is pinned.
3. program is attached to a hook.
4. User mode app is closed ==> This will close program and link handles. 

With the current implementation, the ref count for link handle will become 0 when the app exits in  step 4 above, causing the program to be detached, which should not happen.

With the new lifecycle, the program will still remain attached to the hook after the user mode app has exited.

Scenario: an ebpf program is pinned, and attached to multiple hooks. The user mode app has exited.

**Case1**: Unhook the program from a specific hook.
A new UM process can call query program info for a pinned program. It wil get all the link_info for that program along with the program info. link info will contain the link handle, and then the new app can call detach for a specific link.

**Case2**: Unload and unhook the pinned program from all the hooks.
A new UM process can query program info for the pinned program. It can then call unpin on the program and then close the handle. Once the program handle is closed, its ref count will be 0, which will cause the program to be detached from all the hooks.

**Comment by Alan-Jowett** [comment] 2021-07-28 16:56
This seems overly complicated. Why expose a handle to the link object at all then? Why not simply call link/unlink on the program handle instead? 

In other words, don't expose a link handle at all.

**Comment by saxena-anurag** [comment] 2021-07-28 17:02
1. Linux also returns a link fd when an "attach" happens. The libbpf APIs also return a pointer to UM "ebpf_link" structure which has an embedded fd. Also, in Linux, unlink is called on link fd, and not program fd.
2. If a program is attached to multiple hooks, how will a user detach it from a specific hook, if the unlink call uses program handle?

**Comment by Alan-Jowett** [comment] 2021-07-28 17:07
Can you point me to the linux doc where it says it returns an fd for a link?

https://www.kernel.org/doc/html/latest/userspace-api/ebpf/syscall.html

BPF_PROG_ATTACH and BPF_PROG_DETACH both take a program fd. There is no mention of a link fd.

**Closed** 2021-07-31 00:17 UTC
Labels: ebpf-km, ebpfsvc, triaged
