### ISSUE TITLE
Tracer with this project

### ISSUE THREAD

**Issue by grubeli** [microsoft/ebpf-for-windows#382] opened 2021-08-13 17:43 UTC
There are many syscall tracers build by people based on ebpf on Linux, is it possible to do same on Windows using this project?

**Comment by poornagmsft** [comment] 2021-08-16 15:40
@grubeli Could you provide more details into this request? Did you mean ability to trace what syscalls (or the equivalent on Windows) are called using eBPF or anything else?

**Comment by grubeli** [comment] 2021-08-19 22:36
yes, if that's possible

**Comment by dthaler** [comment] 2021-08-23 15:36
If this is about kprobe hooks, then this is a duplicate of issue #206, so resolving as a duplicate.  Please reopen if this is not covered by that issue.

**Closed by dthaler** 2021-08-23 15:36 UTC
Labels: duplicate, enhancement, question
