### ISSUE TITLE
Implement BPF_CGROUP_INET4_BIND / BPF_CGROUP_INET6_BIND

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#1997] opened 2023-02-01 20:07 UTC
### Describe the feature you'd like supported

This issue is for adding support for BPF_CGROUP_INET4_BIND / BPF_CGROUP_INET6_BIND attach types.

### Proposed solution

Add support for BPF_CGROUP_INET4_BIND / BPF_CGROUP_INET6_BIND. This can use FWPM_LAYER_ALE_BIND_REDIRECT_V4 / FWPM_LAYER_ALE_BIND_REDIRECT_V6 layers for implementing the hook.

**Comment by dahavey** [comment] 2023-02-06 16:43
Duplicate of #333

**Closed** 2023-02-06 16:43 UTC
Labels: duplicate, enhancement, triaged
