### ISSUE TITLE
Make IOCTL call to fetch program context for a program type

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#205] opened 2021-05-19 18:52 UTC
Currently get_program_type_windows() queries a local list of program types to get the program context. This should change to make ioctl call to EC to get the program context.

**Comment by dthaler** [comment] 2021-05-24 16:50
Is this a duplicate of #67?

**Comment by dthaler** [comment] 2021-05-24 17:40
Please close if a duplicate of #67.

**Comment by dthaler** [comment] 2021-06-07 17:42
Verified duplicate since #223 tracks registry issue

**Closed by dthaler** 2021-06-07 17:42 UTC
Labels: duplicate
