### ISSUE TITLE
Unload the droppacket.o while receiving udp packets(with dnsFlood.exe) bugchecked my vm(repro rate 3/3)

### ISSUE THREAD

**Issue by lianghaoGao** [microsoft/ebpf-for-windows#254] opened 2021-06-08 21:14 UTC
Simply loading/unloading the ebpf program seems fine. 
Loading ebpf program while receiving packets seems fine. 
But unloading ebpf program while receiving packets bugchecked the vm.[](url)

**Comment by Alan-Jowett** [comment] 2021-06-08 21:32
Call stack:
```
3: kd> k100
# Child-SP RetAddr Call Site
00 ffff8084`19043e98 fffff800`1e512742 nt!DbgBreakPointWithStatus [minkernel\ntos\rtl\amd64\debugstb.asm @ 124]
01 ffff8084`19043ea0 fffff800`1e511d26 nt!KiBugCheckDebugBreak+0x12 [minkernel\ntos\ke\bugcheck.c @ 658]
02 ffff8084`19043f00 fffff800`1e3f7027 nt!KeBugCheck2+0x946 [minkernel\ntos\ke\bugcheck.c @ 2027]
03 ffff8084`19044610 fffff800`1e408e69 nt!KeBugCheckEx+0x107 [minkernel\ntos\ke\amd64\procstat.asm @ 237]
04 ffff8084`19044650 fffff800`1e405169 nt!KiBugCheckDispatch+0x69 [minkernel\ntos\ke\amd64\trap.asm @ 3770]
05 ffff8084`19044790 fffff800`24624b08 nt!KiPageFault+0x469 [minkernel\ntos\ke\amd64\trap.asm @ 1565]
Unable to load image \??\c:\privates\ebpfcore.sys, Win32 error 0n2
06 ffff8084`19044920 fffff800`2462374d ebpfcore!ebpf_program_invoke+0x18 [E:\ebpf-for-windows\libs\execution_context\ebpf_program.c @ 396]
Unable to load image \??\c:\privates\NetEbpfExt.sys, Win32 error 0n2
07 ffff8084`19044960 fffff800`24641714 ebpfcore!_ebpf_link_instance_invoke+0x4d [E:\ebpf-for-windows\libs\execution_context\ebpf_link.c @ 144]
08 ffff8084`190449a0 fffff800`21bcca51 NetEbpfExt!_net_ebpf_ext_layer_2_classify+0x124 [E:\ebpf-for-windows\netebpfext\net_ebpf_ext.c @ 445]
```

The issue is that the state stored in NetEbpfExt isn't protected by epoch tracking, so we race between client detach and invoking the hook. 

Options are:
1. Export epoch_enter/epoch_leave and have the client detach occur epoch end (by the detach occurring on epoch end)
2. Add a lock in NetEbpfExt to synchronize detach and invoke.

Option 2 is simpler, but 2 will probably tank performance though.

**Comment by Alan-Jowett** [comment] 2021-06-09 15:18
Should be fixed now.

**Closed by Alan-Jowett** 2021-06-09 15:18 UTC
Labels: bug
