### ISSUE TITLE
eBPF verification failed with incorrect stack upper bound check

### ISSUE THREAD

**Issue by zenmiao7** [microsoft/ebpf-for-windows#3360] opened 2024-03-16 08:18 UTC
### code example
```
typedef struct 
{
    uint16_t cipher_suits[50];
    uint8_t cipher_suit_count;
} client_hello_info;

SEC("xdp_test")
int tls_client_hello_tracker(xdp_md_t* ctx)
{
    client_hello_info info;
    for (int i = 0;i < 50; i++)
        info.cipher_suits[i] = 0;

    bpf_ringbuf_output(&client_hello_info_pipe, &info, sizeof(info), 0);
    bpf_printk("Add one message");

    return XDP_PASS;
}
```
### ebpf verification result
```
; C:\Users\User\Source\ebpfSamples/xdp1.c:142
;         info.cipher_suits[i] = 0;
9: Lower bound must be at least 0 (valid_access(r3.offset, width=2) for write)
; C:\Users\User\Source\ebpfSamples/xdp1.c:142
;         info.cipher_suits[i] = 0;
9: Upper bound must be at most EBPF_STACK_SIZE (valid_access(r3.offset, width=2) for write)
; C:\Users\User\Source\ebpfSamples/xdp1.c:144
;     bpf_ringbuf_output(&client_hello_info_pipe, &info, sizeof(info), 0);
19: Stack content is not numeric (valid_access(r2.offset, width=r3) for read)
```

In the code, the size of the array is given. Why the verification still think the array access is not valid?

### OS information

Windows11

### Steps taken to reproduce bug

1. use clang to build code example.
2. netsh ebpf show verification xxx.o

### Expected behavior

Verification succeed.

### Actual outcome

Verification failed.

**Comment by shankarseal** [comment] 2024-03-16 08:28
Please share the .o file and the eBPF version that you are using.

**Comment by zenmiao7** [comment] 2024-03-16 08:49
While debugging with @shankarseal, we find the error is resolve if we rewrite the loop to
```
info.cipher_suits[0] = 0;
info.cipher_suits[1] = 1;
info.cipher_suits[2] = 2;
...
info.cipher_suits[4] = 4;
```

**Comment by dthaler** [comment] 2024-03-18 15:35
Looks like a duplicate of https://github.com/vbpf/ebpf-verifier/issues/441
Workarounds are either:
a) Use the pragma unroll macro to tell the compiler to unroll the loop like you mentioned, or
b) make the loop count down instead of up.  sometimes that will work.

**Comment by dahavey** [comment] 2024-03-18 15:43
Tracked by #1993

**Closed by dahavey** 2024-03-18 15:43 UTC
Labels: bug, triaged
