### ISSUE TITLE
eBPF store APIs read and write separate keys from user and kernel mode

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#3095] opened 2023-11-30 20:09 UTC
### Describe the bug

The kernel mode store helper APIs read and write using HKLM. The user mode store helper APIs read and write using HKCU.

### OS information

N/A.

### Steps taken to reproduce bug

Write to the eBPF store from a driver. Attempt to run user mode tools that rely on the eBPF store, e.g., `netsh ebpf show verification`.

### Expected behavior

The characteristics written to the eBPF store are reliably read from the eBPF store.

### Actual outcome

The characteristics written to the eBPF store are entirely ignored if reader_env != writer_env.

**Comment by shankarseal** [comment] 2023-12-04 05:31
This looks like related to #2382. @saxena-anurag , is this by design?

**Comment by saxena-anurag** [comment] 2023-12-04 05:37
Yes this is by design and is same as #2382. Ideally we need to populate the eBPF store only for offline verification, i.e. for the cases where the extension is not expected to be running. So ideally extensions can skip populating the store if a UM tool is also doing the same and is part of the installation script / MSI.

**Comment by mtfriesen** [comment] 2023-12-04 13:56
How can this be by design? If I understand correctly, the kernel mode store APIs are provided as a static lib (i.e, unserviceable) and the registry keys being written are a black hole. Wouldn't it be equivalent to not provide the kernel APIs at all?

**Comment by mtfriesen** [comment] 2023-12-04 13:59
Note the [documentation ](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/eBpfExtensions.md#27-registering-program-types-and-attach-types---ebpf-store) describes this API as having an effect on the "eBPF store" when in fact there are two disjoint eBPF stores.

**Comment by saxena-anurag** [comment] 2023-12-04 16:43
The only consumer of ebpf store is UM and it tries to get information from the other path if the first is not available. So the store should still be transparent to components writing to it.

Just to give a bit more detail on why 2 stores -- currently ebpf store needs to be populated as part of eBPF build, and updating HKLM requires admin privileges. That will mean a dev needs to run build step as admin, which is not desired.

**Comment by dahavey** [comment] 2023-12-04 17:08
Duplicate of #1231

**Closed as completed by dahavey** 2023-12-04 17:08 UTC
Labels: bug, duplicate, triaged
