### ISSUE TITLE
ebpfapi.dll is pulling in new dependencies in v0.11 release.

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#2861] opened 2023-09-18 02:13 UTC
These modules seem to be new dependencies in this release.
List of well known DLLs pulled in by ebpfapi.dll.
[-] 64-bit KnownDlls : 
  C:\WINDOWS\system32\advapi32.dll
  C:\WINDOWS\system32\bcryptPrimitives.dll
  C:\WINDOWS\system32\clbcatq.dll
  C:\WINDOWS\system32\combase.dll
  C:\WINDOWS\system32\COMCTL32.dll
  C:\WINDOWS\system32\COMDLG32.dll
  C:\WINDOWS\system32\coml2.dll
  C:\WINDOWS\system32\CRYPT32.dll
  C:\WINDOWS\system32\difxapi.dll
  C:\WINDOWS\system32\gdi32.dll
  C:\WINDOWS\system32\gdi32full.dll
  C:\WINDOWS\system32\gdiplus.dll
  C:\WINDOWS\system32\IMAGEHLP.dll
  C:\WINDOWS\system32\IMM32.dll
  C:\WINDOWS\system32\kernel32.dll
  C:\WINDOWS\system32\kernelbase.dll
  C:\WINDOWS\system32\MSCTF.dll
  C:\WINDOWS\system32\msvcp_win.dll
  C:\WINDOWS\system32\MSVCRT.dll
  C:\WINDOWS\system32\NORMALIZ.dll
  C:\WINDOWS\system32\NSI.dll
  C:\WINDOWS\system32\ntdll.dll
  C:\WINDOWS\system32\ole32.dll
  C:\WINDOWS\system32\OLEAUT32.dll
  C:\WINDOWS\system32\PSAPI.DLL
  C:\WINDOWS\system32\rpcrt4.dll
  C:\WINDOWS\system32\sechost.dll
  C:\WINDOWS\system32\Setupapi.dll
  C:\WINDOWS\system32\SHCORE.dll
  C:\WINDOWS\system32\SHELL32.dll
  C:\WINDOWS\system32\SHLWAPI.dll
  C:\WINDOWS\system32\ucrtbase.dll
  C:\WINDOWS\system32\user32.dll
  C:\WINDOWS\system32\win32u.dll
  C:\WINDOWS\system32\WINTRUST.dll
  C:\WINDOWS\system32\WLDAP32.dll
  C:\WINDOWS\system32\wow64.dll
  C:\WINDOWS\system32\wow64base.dll
  C:\WINDOWS\system32\wow64con.dll
  C:\WINDOWS\system32\wow64cpu.dll
  C:\WINDOWS\system32\wow64win.dll
  C:\WINDOWS\system32\WS2_32.dll

generated using [Dependencies tool](https://github.com/lucasg/Dependencies).

Which of these can be moved to delayload and which of these can be totally eliminated. Which of these (if any) are newer dependencies compared to older releases.

**Comment by dahavey** [comment] 2023-09-18 15:55
link /dump /imports ebpfapi.dll

**Comment by saxena-anurag** [comment] 2023-09-27 22:21
Closing this as the issue is understood and resolved now.

**Closed by saxena-anurag** 2023-09-27 22:21 UTC
Labels: optimization, triaged
