### ISSUE TITLE
bpf_prog_test_run_opts should accept the repeat field set to zero

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#3054] opened 2023-11-15 18:53 UTC
### Describe the bug

From public blog posts, it seems libbpf on Linux accepts a `bpf_test_run_opts` `repeat` field set to zero; presumably this is treated as a value of one.

### OS information

N/A.

### Steps taken to reproduce bug

```
bpf_test_run_opts opts;
int prog_fd = ...;

ZeroMemory(&opts);
// Note, some other fields are definitely mandatory, but are not set in our repro code.
Assert::AreEqual(0, bpf_prog_test_run_opts(prog_fd, &opts));
```

### Expected behavior

The API should succeed and execute the program once.

### Actual outcome

https://github.com/microsoft/ebpf-for-windows/issues/3049

### Additional details

[Blog post](https://who.ldelossa.is/posts/unit-testing-ebpf/)

Snippet in blog:

```
        // define our BPF_PROG_RUN options with our mock data.
        struct bpf_test_run_opts opts = {
                // required, or else bpf_prog_test_run_opts will fail
                .sz = sizeof(struct bpf_test_run_opts),
                // data_in will wind up being ctx.data
                .data_in = &v4_pkt,
                .data_size_in = sizeof(v4_pkt),
                // ctx is an skb in this case
                .ctx_in = &skb,
                .ctx_size_in = sizeof(skb)
        };
```

**Comment by dahavey** [comment] 2023-11-20 16:49
Duplicate of #3049

**Closed** 2023-11-20 16:49 UTC
Labels: bug, duplicate, triaged
