### ISSUE TITLE
Test eBPF with driver verifier + low resources simulation

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#2531] opened 2023-05-30 14:33 UTC
### Describe the feature you'd like supported

Adding an eBPF stress test with driver verifier's [low resources simulation ](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/low-resources-simulation) enabled should offer a relatively high ROI, since verifier already implements a variety of low resources simulations within driver verifier hooks. No changes to the driver under test are needed; the only costs are setting up an environment with verifier enabled and collecting system crash dumps.

Since standard Azure Pipelines and GitHub Actions images do not support a reboot step in test jobs, which is a prerequisite for enabling driver verifier, custom agents are required. Using custom images and/or custom CI runner pools is relatively straightforward and benefits other test workloads, since driver verifier should ideally be enabled in non-stress tests, too.

Similarly system crash dumps cannot be collected from the standard CI agents, so custom pools need to be used.

### Proposed solution

Using driver verifier and taking advantage of the existing, high quality hooks for low resources simulation provides another layer of coverage for error handling code paths in eBPF, complementing any existing stress tests eBPF has.

In addition to the improved confidence in customer-facing quality, developers of other projects, including XDP, that use driver verifier can have increased confidence in the reliability of eBPF in stress and low resources environments.

### Additional context
The [XDP](https://github.com/microsoft/xdp-for-windows/) project has been using driver verifier and low resources simulation throughout the development lifecycle, and has found many bugs; unfortunately, most were found before open sourcing to GitHub. Since the XDP stress tests run with verifier enabled on eBPF as well, we've caught several bugs within eBPF without modifying that binary or explicitly targeting it for stress testing.

There is probably more low hanging fruit here an eBPF stress test would discover with the assistance of driver verifier.

**Comment by saxena-anurag** [comment] 2023-06-05 16:03
Duplicate of #2022

**Closed by saxena-anurag** 2023-06-05 16:03 UTC
Labels: enhancement, triaged
