### ISSUE TITLE
.msi Installer fails to provide libbpf includes

### ISSUE THREAD

**Issue by H0mTanks** [microsoft/ebpf-for-windows#2065] opened 2023-02-10 16:43 UTC
### Describe the bug

`libbpf` includes were provided by the 0.5.0 .msi installer, inside `include/libbpf`.
 
However, on building the latest commit of the ebpf-for-windows repo and using the installer from `x64/Debug/ebpf-for-windows.msi`, the `include` folder from the newer installer does not have a libbpf folder. Hence, compiling an eBPF program with the newer include folder fails due to the compiler not finding `libbpf/src/bpf_helpers.h` included in include `bpf_helpers.h`

### OS information

Windows 11

### Steps taken to reproduce bug

1) Build this repo.
2) Use the new installer at `x64/Debug/ebpf-for-windows.msi` to install eBPF development files.
3) Missing `libbpf` includes inside the `include` folder.

### Expected behavior

`libbpf` includes should be placed by the installer in the `include` folder.

### Actual outcome

The `libbpf` includes were missing from the `include` directory.

**Comment by H0mTanks** [comment] 2023-02-16 08:31
Please reopen this issue. The entirety of the `root/include/libbpf` folder was missing. This folder is supposed to have `root/include/libbpf/src` and `root/include/libbpf/include` folders.
This is how it was in the 0.5.0 release.

The above commit puts the contents of the `root/include/libbpf/include` folder inside `root/include/libbpf`.

As such, files like `libbpf/src/bpf_helpers.h` mentioned in the first post of this issue are still missing in the 0.6.0 release and userspace programs which have `#include <bpf/libpf.h>` will fail to build.

**Comment by gtrevi** [comment] 2023-02-27 18:08
@H0mTanks, please note the linked PR is not released in 0.6.0, it should be pulled from the build artifacts for the moment.

- RE: missing `root/include/ebpf_base.h`: I see it is not included in 0.5.0 as well, will eventually add it in an additional PR.
- RE: missing `root/include/libbpf` directory tree: the 0.5.0 directory structure should match what the PR has fixed. Can you please confirm you are using the latest MSI?

Directory structure for `v0.5.0`:
![image](https://user-images.githubusercontent.com/22826130/221643861-9215800a-c1ec-4ff0-b2de-738c4770116a.png)

Directory structure of the latest MSI output (i.e. from the **build artifact in `main`**):

![image](https://user-images.githubusercontent.com/22826130/221644056-18acbe14-745b-4110-b76d-1eb6fa5ffc65.png)

**Comment by H0mTanks** [comment] 2023-02-27 20:13
Okay, this is curious. You're correct that the 0.5.0 .msi release has the same directory structure.

However, my understanding that the 0.5.0 release provided a different directory structure was because I found this `eBPF-for-Windows.0.5.0` folder on my filesystem.
As you can see the `src` folder is present inside `root/libbpf/include`.
![image](https://user-images.githubusercontent.com/59693193/221670321-02de8ab6-7fdc-4af4-8034-75de343ba27b.png)

My bad about 0.5.0 release .msi, but I don't quite remember how I got the above folder. Maybe it wasn't from an .msi installation.

Regardless, if you examine `bpf_helpers.h` in the `root/include` directory. You'll see:
```cpp
// If we're compiling an actual eBPF program, then include
// libbpf's bpf_helpers.h for the rest of the platform-agnostic
// defines.
#ifndef _MSC_VER
#include "libbpf/src/bpf_helpers.h" <-----------------------------
#define bpf_map_def _ebpf_map_definition_in_file
#include "ebpf_nethooks.h"
#endif
```

Therefore, I believe the `src` folder being in the `root/include/libbpf` folder is the correct project structure.
![image](https://user-images.githubusercontent.com/59693193/221672068-70be3989-9750-495b-98c0-be56d592c8b1.png)

Without these files, userspace applications just won't compile because the header files in `root/include` seem to be expecting them.

Some random further info if it helps: The 0.5.0 folder in my filesystem that I showed above seemed to be created last month at 09/01/2023.

**Comment by gtrevi** [comment] 2023-02-28 05:20
@H0mTanks Thanks for the clarification.

The MSI was rebuilt from its ashes, and yes it should provide the same files that nuget provides, although, the nuget packager currently just xcopy-s with wildcards from directories, and btw on the other end it looks like it's missing other files and uses inconsistent directories:

```xml
  <files>
    <file src="Convert-BpfToNative.ps1"                       target="build\native\bin"                    />
    <file src="bpf2c.exe"                                     target="build\native\bin"                    />
    <file src="export_program_info.exe"                       target="build\native\bin"                    />
    <file src="ebpfapi.dll"                                   target="build\native\bin"                    />
    <file src="ebpfapi.lib"                                   target="build\native\lib"                    />
    <file src="..\..\include\**\*.*"                          target="build\native\include"                />
    <file src="..\..\external\bpftool\libbpf\include\**\*.*"  target="build\native\include\libbpf\include" />
    <file src="..\..\external\bpftool\libbpf\src\**\*.h"      target="build\native\include\libbpf\src"     />
    <file src="..\..\external\ebpf-verifier\src\ebpf_base.h"  target="build\native\include"                />
    <file src="..\..\tools\nuget\README.md"                   target="."                                   />
    <file src="..\..\tools\nuget\ebpf-for-windows.props"      target="build\native"                        />
  </files
```

RE: *I'm quite unsure at this point what the correct structure is supposed to be*: just to lay out the rationals, the MSI by design tracks each file/action as an individual component, and therefore implements transactional, repeatable and deterministic releases, whereas nuget packaging - done as currently done through wildcards - is not a best practice for release purposes, in order to achieve precise tracking of what is being shipped... especially when wildcards are applied to external projects.

Therefore, the right solution requires a fix to both: integrating the MSI with the *just* the required files, refining the nuget packager to *punctually* source files, over lazy wildcard-copying.

**Comment by H0mTanks** [comment] 2023-02-28 05:36
Make sense, the ideal experience I'm looking for is to install the .msi and have the includes work themselves out. I'll stick to the nuget package until then I guess.

**Comment by gtrevi** [comment] 2023-02-28 06:21
Yes please, and thanks from bringing this up. As we get close to release, it is important to shave off typical development shortcuts/overlooks that have been taken so far.

**Closed** 2023-03-07 02:07 UTC
Labels: bug, triaged
