### ISSUE TITLE
Platform abstraction layer for kernel mode needs tests in CI/CD

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#184] opened 2021-05-12 22:16 UTC
Platform abstraction layer for kernel mode needs tests in CI/CD

Currently we only test the user mode PAL.

**Comment by Alan-Jowett** [comment] 2021-05-13 15:23
Needs investigation:
Does the GitHub CI/CD pipeline permit loading unsigned drivers?

**Comment by dthaler** [comment] 2021-05-24 17:48
Duplicate of #141

**Closed** 2021-05-24 17:48 UTC
Labels: duplicate, enhancement
