### ISSUE TITLE
rpc_interface.idl contains a duplicate of EbpfMapDescriptor 

### ISSUE THREAD

**Issue by saxena-anurag** [microsoft/ebpf-for-windows#208] opened 2021-05-19 21:26 UTC
rpc_interface.idl currently has a duplicate definition of EbpfMapDescriptor. EbpfMapDescriptor is defined in spec_type_descriptors.hpp and that header file includes "vector" and "string". So spec_type_descriptors.hpp cannot be directly included in the IDL file.

**Comment by dthaler** [comment] 2021-05-24 17:59
Is this a duplicate of #153?

**Closed** 2021-05-24 18:00 UTC
Labels: cleanup, duplicate
