### ISSUE TITLE
Update and replace operations for any dynamically allocated maps show degraded performance.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2949] opened 2023-10-05 15:16 UTC
![image](https://github.com/microsoft/ebpf-for-windows/assets/20480683/beac22e9-966e-42df-9f51-2508deecdd07)

**Comment by Alan-Jowett** [comment] 2023-10-05 15:54
Before:
![image](https://github.com/microsoft/ebpf-for-windows/assets/20480683/faab30a6-23f4-43ab-a3bb-6b48162ab617)

After:
![image](https://github.com/microsoft/ebpf-for-windows/assets/20480683/2e9476b7-c88c-4b50-8a37-13b0e99ca037)

Cost of heap allocations was being attributed to DPC and not to the BPF program, which resulted in numbers being reported below expected values.

**Comment by shankarseal** [comment] 2023-10-09 16:05
This is not a perf regression - just how we are accounting for time spent on freeing memory.

**Comment by shankarseal** [comment] 2023-10-09 16:06
Closing this as this is not a bug/optimization issue.

**Closed by shankarseal** 2023-10-09 16:06 UTC
Labels: wontfix, optimization
