### ISSUE TITLE
msbuild failed: Your project does not reference ".NETFramework,Version=v4.0"

### ISSUE THREAD

**Issue by williamtu** [microsoft/ebpf-for-windows#635] opened 2021-10-09 14:03 UTC
Hi, I'm trying to compile the project but got a few errors
I looked at #488, but still couldn't get my build working.
Any comments are welcome, [thanks!](url)

PS C:\ebpf-for-windows> nuget.exe
NuGet Version: 5.11.0.10

PS C:\ebpf-for-windows> cmake -S external\ebpf-verifier -B external\ebpf-verifier\build
```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
Feeds used:
  C:\Users\Administrator\.nuget\packages\
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Package "Boost.1.75.0" is already installed.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ebpf-for-windows/external/ebpf-verifier/build
```
PS C:\ebpf-for-windows> nuget restore ebpf-for-windows.sln
```
MSBuild auto-detection: using msbuild version '16.11.0.36601' from 'c:\BuildTools\MSBuild\Current\Bin'.
All packages listed in packages.config are already installed.
WARNING: NU1603: ebpfverifier depends on boost (>= 1.75.5) but boost 1.75.5 was not found. An approximate best
 match of boost 1.76.0 was resolved.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\ebpf-for-windows\external\ebpf-verifier\bu
ild\obj\project.assets.json
Restored C:\ebpf-for-windows\external\ebpf-verifier\build\ebpfverifier.vcxproj (in 98 ms).

NuGet Config files used:
    C:\Users\Administrator\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
1 of 2 projects are up-to-date for restore.
```
PS C:\ebpf-for-windows> msbuild /m /p:Configuration=Debug /p:Platform=x64 ebpf-for-windows.sln
```
Build FAILED.

       "C:\ebpf-for-windows\ebpf-for-windows.sln" (default target) (1) ->
       "C:\ebpf-for-windows\netebpfext\netebpfext.vcxproj.metaproj" (default target) (12) ->
       "C:\ebpf-for-windows\netebpfext\netebpfext.vcxproj" (default target) (33) ->
       (InfVerif target) ->
         C:\ebpf-for-windows\netebpfext\NetEbpfExt.inf(56-56): warning 2083: Section [defaultuninstall] not r
       eferenced or used. [C:\ebpf-for-windows\netebpfext\netebpfext.vcxproj]
         C:\ebpf-for-windows\netebpfext\NetEbpfExt.inf(59-59): warning 2083: Section [defaultuninstall.servic
       es] not referenced or used. [C:\ebpf-for-windows\netebpfext\netebpfext.vcxproj]


       "C:\ebpf-for-windows\ebpf-for-windows.sln" (default target) (1) ->
       "C:\ebpf-for-windows\tests\client\ebpf_client.vcxproj.metaproj" (default target) (13) ->
       "C:\ebpf-for-windows\ebpfsvc\eBPFSvc.vcxproj" (default target) (17) ->
       "C:\ebpf-for-windows\external\ebpf-verifier\build\ebpfverifier.vcxproj" (default target) (21) ->
       "C:\ebpf-for-windows\external\ebpf-verifier\build\ZERO_CHECK.vcxproj" (default target) (25) ->
       (ResolveNuGetPackageAssets target) ->
         c:\BuildTools\MSBuild\Microsoft\NuGet\16.0\Microsoft.NuGet.targets(198,5): error : Your project does
        not reference ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0"
        in the "TargetFrameworks" property of your project file and then re-run NuGet restore. [C:\ebpf-for-w
       indows\external\ebpf-verifier\build\ZERO_CHECK.vcxproj]


       "C:\ebpf-for-windows\ebpf-for-windows.sln" (default target) (1) ->
       "C:\ebpf-for-windows\tests\client\ebpf_client.vcxproj.metaproj" (default target) (13) ->
       "C:\ebpf-for-windows\ebpfsvc\eBPFSvc.vcxproj" (default target) (17) ->
       "C:\ebpf-for-windows\libs\service\service.vcxproj" (default target) (23) ->
       (ClCompile target) ->
         C:\ebpf-for-windows\libs\service\windows_platform_service.cpp(18,5): error C2440: 'initializing': ca
       nnot convert from 'EbpfHelperPrototype (__cdecl *)(int32_t)' to 'ebpf_get_helper_prototype_fn' [C:\ebp
       f-for-windows\libs\service\service.vcxproj]
         C:\ebpf-for-windows\libs\service\windows_platform_service.cpp(19,5): error C2440: 'initializing': ca
       nnot convert from 'bool (__cdecl *)(int32_t)' to 'ebpf_is_helper_usable_fn' [C:\ebpf-for-windows\libs\
       service\service.vcxproj]


       "C:\ebpf-for-windows\ebpf-for-windows.sln" (default target) (1) ->
       "C:\ebpf-for-windows\libs\api\api.vcxproj.metaproj" (default target) (7) ->
       "C:\ebpf-for-windows\libs\api\api.vcxproj" (default target) (26) ->
         C:\ebpf-for-windows\libs\api\windows_platform.cpp(78,5): error C2440: 'initializing': cannot convert
        from 'EbpfHelperPrototype (__cdecl *)(int32_t)' to 'ebpf_get_helper_prototype_fn' [C:\ebpf-for-window
       s\libs\api\api.vcxproj]
         C:\ebpf-for-windows\libs\api\windows_platform.cpp(79,5): error C2440: 'initializing': cannot convert
        from 'bool (__cdecl *)(int32_t)' to 'ebpf_is_helper_usable_fn' [C:\ebpf-for-windows\libs\api\api.vcxp
       roj]

    2 Warning(s)
    5 Error(s)
```
full log here
[log.txt](https://github.com/microsoft/ebpf-for-windows/files/7315766/log.txt)

**Comment by dahavey** [comment] 2021-10-11 15:58
Closed as duplicate of #488

**Closed** 2021-10-11 15:58 UTC
